# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DemoPod' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DemoPod
  pod 'CLTNearNetworking', :git => 'https://github.com/cclovett/CLTNearNetworking.git', :branch => 'master'
end
